
### TEST 1: get recommendation for profile by ID 

GET http://localhost:8000/recommend/crm_11
Authorization: personalization_test

### TEST 2: get recommendation for profile by ID with top_n

GET http://localhost:8000/recommend/crm_11?top_n=3
Authorization: personalization_test

### TEST 3: get recommendation for profile by ID with top_n, except_product_ids, in_journey_maps

GET http://localhost:8000/recommend/crm_16?top_n=5&except_product_ids=item_1,item_6&in_journey_maps=da-lat
Authorization: personalization_test

### TEST 4: check profile for recommendation

POST http://localhost:8000/check-profile-for-recommendation/
content-type: application/json
Authorization: personalization_test

{
        "profile_id": "crm_99",
        "page_view_keywords": ["Electronics","Macbook", "Drone"],
        "purchase_keywords": ["lenovo", "nvidia"],
        "interest_keywords": ["travel", "reading"],
        "additional_info": {"age": 38, "location": "Vietnam"},
        "journey_maps": ["coffee-shop", "sapa"]
}

### TEST 5: check profile for recommendation with top_n, except_product_ids 

POST http://localhost:8000/check-profile-for-recommendation/
content-type: application/json
Authorization: personalization_test

{
        "profile_id": "crm_99",
        "page_view_keywords": ["Camera","travel", "Drone"],
        "purchase_keywords": ["lenovo", "nvidia"],
        "interest_keywords": ["adventure", "Travel"],
        "additional_info": {"age": 38, "location": "Vietnam"},
        "max_recommendation_size": 5,
        "except_product_ids" : ["item_10","item_5"],
        "journey_maps": ["phu-quoc"]
}